lib/miniature_sniffle_web/router.ex
defmodule MiniatureSniffleWeb.Router do
  use MiniatureSniffleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_user
  end

  scope "/user/", MiniatureSniffleWeb do
    pipe_through [:browser, :authenticate]

    get "/create_order", OrderController, :new
    post "/create_order", OrderController, :create
  end

  scope "/", MiniatureSniffleWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/comeonin", AccountController, :index
    post "/comeonin", AccountController, :login
    get "/logout", AccountController, :logout
  end

  defp assign_user(conn, _options) do
    # allow assigns to be set up and preserved for unit tests
    if Mix.env() == :test and Map.has_key?(conn.assigns, :user) do
      conn
    else
      assign(conn, :user, get_session(conn, :user))
    end
  end

  defp authenticate(conn, _options) do
    if conn.assigns.user do
      conn
    else
      conn
      |> put_flash(:error, "You must be logged in to view that page.")
      |> redirect(to: "/comeonin")
      |> halt()
    end
  end
end

lib/miniature_sniffle_web/views/layout_view.ex
defmodule MiniatureSniffleWeb.LayoutView do
  use MiniatureSniffleWeb, :view
end

lib/miniature_sniffle_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>MiniatureSniffle · Powered by Phoenix</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if @conn.assigns.user do %>
              <li><%= link("Log out", to: Routes.account_path(@conn, :logout)) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>